---
- name: Check Pyenv Installation
  shell: source /home/ubuntu/.zshrc &> /dev/null && pyenv versions
  args:
    executable: /bin/zsh
  register: is_pyenv_installed
  ignore_errors: yes
- debug: var=is_pyenv_installed

- name: Install pyenv
  shell: curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
  when: is_pyenv_installed.rc != 0

- name: Update zshrc - Pyenv Path
  lineinfile: dest=/home/ubuntu/.zshrc state=present line="export PATH=\"$HOME/.pyenv/bin:$PATH\""
- name: Update zshrc - Pyenv eval pyenv
  lineinfile: dest=/home/ubuntu/.zshrc state=present line="eval \"$(pyenv init -)\""
- name: Update zshrc - Pyenv eval pyenv
  lineinfile: dest=/home/ubuntu/.zshrc state=present line="eval \"$(pyenv virtualenv-init -)\""
